<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" total="4" passed="1">
  <reporter-output>
    <line>
      <![CDATA[ActitimeSuite--> started.....]]>
    </line>
    <line>
      <![CDATA[SmokeTest-->  block is started..]]>
    </line>
    <line>
      <![CDATA[testInvalidLogin--> Test method is started..]]>
    </line>
    <line>
      <![CDATA[testInvalidLogin--> Test method is failed..]]>
    </line>
    <line>
      <![CDATA[createUser--> Test method is started..]]>
    </line>
    <line>
      <![CDATA[createUser--> Test method is failed..]]>
    </line>
    <line>
      <![CDATA[deleteUser--> Test method is skipped..]]>
    </line>
    <line>
      <![CDATA[testInvalidLogin--> Test method is started..]]>
    </line>
    <line>
      <![CDATA[testInvalidLogin--> Test method is pass..]]>
    </line>
  </reporter-output>
  <suite name="ActitimeSuite" duration-ms="78724" started-at="2019-09-09T16:00:59Z" finished-at="2019-09-09T16:02:18Z">
    <groups>
    </groups>
    <test name="SmokeTest" duration-ms="78724" started-at="2019-09-09T16:00:59Z" finished-at="2019-09-09T16:02:18Z">
      <class name="scripts.TestValidLogin">
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:scripts.TestValidLogin@dca536]" name="launchApplication" is-config="true" duration-ms="19161" started-at="2019-09-09T21:30:59Z" finished-at="2019-09-09T21:31:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="testInvalidLogin()[pri:0, instance:scripts.TestValidLogin@dca536]" name="testInvalidLogin" duration-ms="15324" started-at="2019-09-09T21:31:18Z" finished-at="2019-09-09T21:31:33Z">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for title to be "actiTIME - Enter Time-Track123". Current title: "actiTIME - Login" (tried for 5 second(s) with 500 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'VIKASH-PC', ip: '192.168.31.143', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.132, chrome: {chromedriverVersion: 76.0.3809.126 (d80a294506b4..., userDataDir: C:\Users\vikash\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:49467}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 34a38de59dace272b92c9de5d7010210]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for title to be "actiTIME - Enter Time-Track123". Current title: "actiTIME - Login" (tried for 5 second(s) with 500 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'VIKASH-PC', ip: '192.168.31.143', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 76.0.3809.132, chrome: {chromedriverVersion: 76.0.3809.126 (d80a294506b4..., userDataDir: C:\Users\vikash\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:49467}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 34a38de59dace272b92c9de5d7010210
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at scripts.TestValidLogin.testInvalidLogin(TestValidLogin.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
            <line>
              <![CDATA[testInvalidLogin--> Test method is failed..]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:scripts.TestValidLogin@dca536]" name="closeApplication" is-config="true" duration-ms="2985" started-at="2019-09-09T21:31:33Z" finished-at="2019-09-09T21:31:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testInvalidLogin status=FAILURE method=TestValidLogin.testInvalidLogin()[pri:0, instance:scripts.TestValidLogin@dca536] output=testInvalidLogin--> Test method is failed..]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- scripts.TestValidLogin -->
      <class name="scripts.Demo">
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:scripts.Demo@17246de]" name="launchApplication" is-config="true" duration-ms="21750" started-at="2019-09-09T21:31:36Z" finished-at="2019-09-09T21:31:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="createUser()[pri:0, instance:scripts.Demo@17246de]" name="createUser" duration-ms="0" started-at="2019-09-09T21:31:58Z" finished-at="2019-09-09T21:31:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at scripts.Demo.createUser(Demo.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createUser--> Test method is failed..]]>
            </line>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:scripts.Demo@17246de]" name="closeApplication" is-config="true" duration-ms="3195" started-at="2019-09-09T21:31:58Z" finished-at="2019-09-09T21:32:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createUser status=FAILURE method=Demo.createUser()[pri:0, instance:scripts.Demo@17246de] output=createUser--> Test method is failed..]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method status="SKIP" signature="deleteUser()[pri:0, instance:scripts.Demo@17246de]" name="deleteUser" duration-ms="0" started-at="2019-09-09T21:32:01Z" depends-on-methods="scripts.Demo.createUser" finished-at="2019-09-09T21:32:01Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Demo.deleteUser()[pri:0, instance:scripts.Demo@17246de] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Demo.deleteUser()[pri:0, instance:scripts.Demo@17246de] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
      </class> <!-- scripts.Demo -->
      <class name="scripts.TestInvalidLogin">
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:scripts.TestInvalidLogin@f67ac7]" name="launchApplication" is-config="true" duration-ms="15819" started-at="2019-09-09T21:32:01Z" finished-at="2019-09-09T21:32:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="PASS" signature="testInvalidLogin()[pri:0, instance:scripts.TestInvalidLogin@f67ac7]" name="testInvalidLogin" duration-ms="113" started-at="2019-09-09T21:32:17Z" finished-at="2019-09-09T21:32:17Z">
          <reporter-output>
            <line>
              <![CDATA[testInvalidLogin--> Test method is pass..]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:scripts.TestInvalidLogin@f67ac7]" name="closeApplication" is-config="true" duration-ms="327" started-at="2019-09-09T21:32:17Z" finished-at="2019-09-09T21:32:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testInvalidLogin status=SUCCESS method=TestInvalidLogin.testInvalidLogin()[pri:0, instance:scripts.TestInvalidLogin@f67ac7] output=testInvalidLogin--> Test method is pass..]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- scripts.TestInvalidLogin -->
    </test> <!-- SmokeTest -->
  </suite> <!-- ActitimeSuite -->
</testng-results>
